### PR TITLE
My license request :)

### PR DESCRIPTION
**Pull request by Bluscream**

### CODE REVIEW

**Comment by cydolo** [comment]
UUID of the Identity

**Comment by Bluscream** [comment]
> 
> 
> UUID of the Identity

You mean the private key? 🤔

**Comment by cydolo** [comment]
UniqueID

**Comment by Bluscream** [comment]
That is my unique ID 
image

**Comment by Bluscream** [comment]
> 
> 
> How can i Import the License/My UUID`?

Click on the heart in the lower right corner.

**Pull request closed without merging**
